### ISSUE TITLE
potentially put file chunk in a different bucket 

### ISSUE THREAD

**Issue by bytesun** [gabrielnic/motoko-cdn#3] opened 2022-01-23 18:30 UTC
The current logic is checking the available bucket before putting every file chunk into bucket as below code,  then potentially some chunks will be put in a different new created bucket when the bucket is full during the uploading, right? why not reserving the space when the file info is created, then keep putting all chunks in the same bucket? @gabrielnic 

```
public func putFileChunks(fileId: FileId, chunkNum : Nat, fileSize: Nat, chunkData : Blob) : async () {
    let b : Bucket = await getEmptyBucket(?fileSize);
    let _ = await b.putChunks(fileId, chunkNum, chunkData);
  };  
```

**Comment by gabrielnic** [comment] 2022-01-24 15:09
Hi, I'm already doing that, but when the file info is first created, not when uploading chunks.
https://github.com/gabrielnic/motoko-cdn/blob/b580dcaddd0c8832c111f50b984d65cc0cd2fe7c/src/backend/Container.mo#L136

**Comment by bytesun** [comment] 2022-01-24 17:12
> s full during

yes, just don't understand why still call "await getEmptyBucket(?fileSize);" when put chunks.

**Comment by gabrielnic** [comment] 2022-01-24 18:03
Well because I don't know exactly the canister id so I need to get it somehow. Otherwise I will have to pass the canister to the front-end once the file info is created and pass it back which is not ideal and don't want to rely on the front-end for that.

**Comment by bytesun** [comment] 2022-01-24 18:19
> Well because I don't know exactly the canister id so I need to get it somehow. Otherwise I will have to pass the canister to the front-end once the file info is created and pass it back which is not ideal and don't want to rely on the front-end for that.

thanks for explanation.  I am trying to add one more state for mapping file to canister, 

` private let _fileIdToBaseket : HashMap.HashMap<FileId, Principal> = HashMap.fromIter(_fileIdToBasketState.vals(), 100, Text.equal, Text.hash);
`
by doing this:
1. get canister id by fileid
```
// let b : Bucket = await getEmptyBucket(?fileSize);
          let bid = _fileIdToBaseket.get(fileId);
          switch(bid){
            case(?bid){
                let r =  do ? {
                    let b : Bucket = (await getBucket(bid))!;          
                    let _ = await b.putChunks(fileId, chunkNum, chunkData);
                   
                    ?1;
                  };  
                
                  #ok(1)
            };
            case(_){
              #err("Can not find the bucket by fileid:" # fileId)
            }
          }
```
2. fetch file without canister id needed in the frontend:

```
 // get file info
  public func fetchFileInfo(fileId : FileId) : async ?FileData {
    let cid = _fileIdToBaseket.get(fileId);
    switch(cid){
      case(?cid){
        do ? {
          let b : Bucket = (await getBucket(cid))!;
          return await b.getFileInfo(fileId);
        }   
      };
      case(_){
        null
      }
    }
    
  };

```

**Comment by gabrielnic** [comment] 2022-02-02 17:00
Hmm, well not sure I follow your logic. I mean each file already knows the canister ID so not sure you need this line ` let cid = _fileIdToBaseket.get(fileId);`

The logic is the following: 

- Once you create the file info return all the info not the just the id including the canister ID. 
- use the received canister ID and pass it to the backend to upload the chunks. 

The problem is even if you know the canister id you still need to fetch it so even if you pass it you still need the logic to fetch it from `Array.find<?CanisterState<Bucket, Nat>`. Yes I can see the advantage that the call to get the bucket won't be async.  So I might refactor that.  

If that's all please close this ticket.

**Closed as completed** 2022-02-02 22:18 UTC
